### DISCUSSION TITLE
3.2.2版本casdoor登录404

### DISCUSSION THREAD

**Discussion by Erhao** [apache/dolphinscheduler#16819] [General]
./api-server/conf/application.yaml:
```
security:
  authentication:
    # Authentication types (supported types: PASSWORD,LDAP,CASDOOR_SSO)
    type: CASDOOR_SSO
    casdoor:
      endpoint: "https://casdoor.mktindex.com/"
      client-id: "2e03fdxxxxxxxxxxxxxe5"
      client-secret: "d895xxxxxxxxxxxxxxxxxxxxxxxded"
      organization-name: "built-in"
      application-name: "DolphinScheduler"
      redirect-url: "https://dolphinscheduler-dev.mktindex.com/dolphinscheduler/ui/login"
```

casdoor应用配置:
![image](https://github.com/user-attachments/assets/09e5b2a4-4de2-4ad2-b01b-95a55a58588a)

ds点击登录后404
![image](https://github.com/user-attachments/assets/475c2a58-e461-47eb-9751-26dd98f7cafa)
![image](https://github.com/user-attachments/assets/5629502d-8660-4c98-a9c3-ee6e1d344d72)
URL为 `https://dolphinscheduler-dev.example.com/login/oauth/authorize?client_id=&response_type=code&redirect_uri=&scope=read&state=be3e666d-3ad6-4c18-afde-de6936505fc7`

还需要其他配置吗? 请指点
