### DISCUSSION TITLE
Casdoor integration with DolphinScheduler redirects to login page after authentication

### DISCUSSION THREAD

**Discussion by Geethika-sg** [apache/dolphinscheduler#16882] [Q&A]
Trying to integrate Casdoor SSO with DolphinScheduler.

My settings in application.yaml file is (Path : /apps/apache-dolphinscheduler/api-server/conf/application.yaml ) :

```
security:
  authentication:
    # Authentication types (supported types: PASSWORD,LDAP,CASDOOR_SSO)
    type: CASDOOR_SSO
casdoor:
  # Your Casdoor server url
  endpoint: "http://ip_casdoor:8000/"
  client-id: "Client_ID_from_casdoor"
  client-secret: "Client_secret_from_casdoor"
  # The certificate may be multi-line, you can use `|-` for ease
  certificate: "-----BEGIN CERTIFICATE-----|-
  cert details
 -----END CERTIFICATE-----"
  # Your organization name added in Casdoor
  organization-name: "built-in"
  # Your application name added in Casdoor
  application-name: "dolphin_application"
  # Doplhinscheduler login url
  redirect-url: "https://dolphinqa.abc.com/dolphinscheduler/ui/login"
```
Dolphinscheduler is accessed via port 12346 (SSL Port)

Redirect URI given in Casdoor Application settings : https://dolphinqa.abc.com/dolphinscheduler/ui/login/callback
after attempting to log in via Casdoor SSO , I get redirected back to the DolphinScheduler login page with the error:
**“State inconsistency and state or code not pair.”** 

Also, sometimes it leads to a blank page after providing casdoor credentials which I am using is

username : admin
Password : 123

(Default credentials)
I have already created application for dolphinscheduler in casdoor and this application is linked to Organization (built-in) and the user (admin)

Dolphinscheduler version used : 3.2.2

Any pointers would be greatly appreciated!
