### DISCUSSION TITLE
helm 部署，怎么去配置 casdoor 呢

### DISCUSSION THREAD

**Discussion by wfy-belief** [apache/dolphinscheduler#17012] [Q&A]
目前尝试在 values 文件配置, 发现不行
```
security:
  authentication:
    type: CASDOOR_SSO

casdoor:
  endpoint: https://xx
  client-id: xx
  client-secret: xx
  redirect-url: xx
  organization-name: 11
    # Your application name added in Casdoor
  application-name: 22
```
