### ISSUE TITLE
[Bug] [dolphinscheduler-api] When connecting to ldap, ldap users cannot log in

### ISSUE THREAD

**Issue by wangw111** [apache/dolphinscheduler#10386]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

当配置 conf/application-api.properties 为ldap认证时

```
security.authentication.type=LDAP
ldap.urls=ldap://xx.xx.xx.xx:389
ldap.base.dn=cn=users,cn=accounts,dc=hadoop,dc=com
ldap.username=cn=Directory Manager
ldap.password=xxxx
ldap.user.identity.attribute=uid
ldap.user.email.attribute=mail
```

![image](https://user-images.githubusercontent.com/28641261/172813992-8dda359b-798c-40ad-8da5-909b98a692f4.png)

### What you expected to happen

报错是用户停用，查询数据库发现 
```
           id: 2
    user_name: user1
user_password: NULL
    user_type: 1
        email: user1@hadoop.com
        phone: NULL
    tenant_id: 0
  create_time: 2022-06-08 11:01:43
  update_time: 2022-06-08 11:01:43
        queue:
        state: 0
```

state状态为0

代码中创建从ladp读取的用户state默认都是0，这样对接ladp后，ladp中的用户仍然不能登录

### How to reproduce

操作如上，配置任何ladp均会出现上述现象。

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
