### ISSUE TITLE
[Bug] [UI] Storage not enabled

### ISSUE THREAD

**Issue by lhcg** [apache/dolphinscheduler#11404]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

What happened
I set values.xml
```
sharedStoragePersistence:
enabled: true
mountPath: "/opt/soft"
accessModes:
- "ReadWriteMany"
## storageClassName must support the access mode: ReadWriteMany
storageClassName: "ds-shared-nfs"
storage: "2Gi"
```
```
fsFileResourcePersistence:
enabled: true
accessModes:
- "ReadWriteMany"
## storageClassName must support the access mode: ReadWriteMany
storageClassName: "ds-file-nfs"
storage: "2Gi"
```

`DATA_BASEDIR_PATH: "/tmp/dolphinscheduler"
RESOURCE_STORAGE_TYPE: "HDFS"
RESOURCE_UPLOAD_PATH: "/dolphinscheduler"
FS_DEFAULT_FS: "file:///"`

### What you expected to happen

It's show "Storage is not enabled" when I upload the spark-examples_2.11-2.4.7.jar.

### How to reproduce

storageClassName: "ds-shared-nfs"
storageClassName: "ds-file-nfs"
all bound 
It's use the nfs.

### Anything else

root@dolphinscheduler-api-dbcf78666-72wff:/opt/dolphinscheduler/conf# pwd
/opt/dolphinscheduler/conf
root@dolphinscheduler-api-dbcf78666-72wff:/opt/dolphinscheduler/conf# cat common.properties 
```
data.basedir.path=/tmp/dolphinscheduler
resource.storage.type=NONE
resource.upload.path=/dolphinscheduler
fs.defaultFS=file:///
```
 why?

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KyleZhang0536** [comment]
Does it mean I have to modify common.properties in 3.0.0 ?

**Comment by itzhang89** [comment]
I deploy the 3.0.0-release by helm and take place the same issue when I try to upload the file to File Manager. 

```yaml
common:
  ## Configmap
  configmap:
    DOLPHINSCHEDULER_OPTS: ""
    DATA_BASEDIR_PATH: "/tmp/dolphinscheduler"
    RESOURCE_STORAGE_TYPE: "HDFS"
    RESOURCE_UPLOAD_PATH: "/dolphinscheduler"
    FS_DEFAULT_FS: "file:///"
```

I check the source code. and find the`RESOURCE_STORAGE_TYPE` value seem not take effect on the api module. The value is alway is None and not parse from the environment.
