### ISSUE TITLE
[Bug] [K8s] Deploy failed when change api service type to NodePort

### ISSUE THREAD

**Issue by qingwli** [apache/dolphinscheduler#12684]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Deployed ds on k8s cluster using office document, change api service type to `NodePort`, and set NodePort and failed.

### What you expected to happen

```
service:
    ## type determines how the Service is exposed. Defaults to ClusterIP. Valid options are ExternalName, ClusterIP, NodePort, and LoadBalancer
    type: "NodePort"
    ## clusterIP is the IP address of the service and is usually assigned randomly by the master
    clusterIP: ""
    ## nodePort is the port on each node on which this service is exposed when type=NodePort
    nodePort: "31057"
```
```
Error: INSTALLATION FAILED: Service "dolphinscheduler-api" is invalid: spec.ports[1].nodePort: Duplicate value: 31057
```    

### How to reproduce

Due https://github.com/apache/dolphinscheduler/pull/10653, `api-port` and `python-api-port` using the same nodeport, will not pass by k8s.

I'll open a PR to fix this bug.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
