### ISSUE TITLE
[Feature][Metrics] Add metrics for workflow runtime

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#13552]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

If most of times, we want to monitor the workflow at workflow level.
e.g. 
```
workflowA:
        executeCount: 3
        successCount: 1
        failedCount:  2
        failoverCount: xx
        successTaskCount: xx
```
Can we output this to Prometheus?
At the workflow level, the label count should be acceptable.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
