### ISSUE TITLE
[Bug] [K8S] projectname is missing

### ISSUE THREAD

**Issue by Gallardot** [apache/dolphinscheduler#14651]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Create a K8S task.  Some parameters of ds are transformed into environment variables passed to the pod of k8s.
But you'll notice that `system.project.name` is empty in the environment variable.

```yaml
    spec:
      containers:
        - name: aaa-2
          image: busyboy:latest
          env:
            - name: taskInstanceId
              value: '2'
            - name: system.task.definition.name
              value: aaa
            - name: system.project.name
            - name: system.project.code
              value: '10377893770976'
            - name: system.workflow.instance.id
              value: '2'
            - name: system.biz.curdate
              value: '20230728'
            - name: system.biz.date
              value: '20230727'
            - name: system.task.instance.id
              value: '2'
            - name: system.workflow.definition.name
              value: '1111'
            - name: system.task.definition.code
              value: '10377975344097'
            - name: system.workflow.definition.code
              value: '10377979443552'
            - name: system.datetime
              value: '20230728094029'
          resources:
            limits:
              cpu: '2'
              memory: 40Mi
            requests:
              cpu: '1'
              memory: 20Mi
```

### What you expected to happen

`system.project.name` should be passed correctly

### How to reproduce

As described above

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
