### ISSUE TITLE
[Improvement] [Helm] `bitnami/postgresql` sub chart and default configurations should be upgraded

### ISSUE THREAD

**Issue by icefery** [apache/dolphinscheduler#14672]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

For the chart `dolphinscheduler-helm-3.1.7`, sub chart `bitnami/postgresql-10.3.18`(default docker images) is incompatible with `arm64`.

When upgrading the `bitnami/postgresql` sub chart version, its configurations have changed, in order to get it working, there are some changes:

- `Chart.yaml`

  ```yaml
  dependencies:
  - name: postgresql
    version: 12.7.1
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.enabled
  ```

- `values.yaml`

  ```yaml
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          postgresPassword: postgres
          username: dolphinscheduler
          password: dolphinscheduler
          database: dolphinscheduler
  ```

- `templates/_helpers.tpl`

  ```yaml
  - name: SPRING_DATASOURCE_USERNAME
    {{- if .Values.postgresql.enabled }}
    value: {{ .Values.postgresql.global.postgresql.auth.username }}
    {{- end }}
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        {{- if .Values.postgresql.enabled }}
        name: {{ template "dolphinscheduler.postgresql.fullname" . }}
        key: password
        {{- end }}
  {{- end -}}
  ```

### What you expected to happen

The version of sub charts are newer, and compatible with default `Chart.yaml`, `values.yaml`, 'templates/*'.

### How to reproduce

See 'What happened'.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
