### ISSUE TITLE
[Feature][Flink-CDC] Support FlinkCDC Task

### ISSUE THREAD

**Issue by kissycn** [apache/dolphinscheduler#16207]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Apache DolphinScheduler is a distributed workflow task scheduling system that supports various types of data workflow tasks. Currently, DolphinScheduler supports basic Flink tasks, but is not yet able to directly support FlinkCDC tasks. FlinkCDC is a library commonly used for real-time data synchronization and change data capture (CDC), which is particularly important for modern data architecture. Currently, FlinkCDC3.0 already supports submitting CDC tasks in the Pipeline mode, which will be very suitable for submitting tasks as a Task plug-in for DolphinScheduler.

### Use case

In the task submission page, in addition to the dolphinscheduler basic parameters, you can submit the Flink-CDC Pipeline yaml declaration file
```yaml
   source:
     type: mysql
     hostname: localhost
     port: 3306
     username: root
     password: 123456
     tables: app_db.\.*

   sink:
     type: doris
     fenodes: 127.0.0.1:8030
     username: root
     password: ""

   pipeline:
     name: Sync MySQL Database to Doris
     parallelism: 2
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
