### ISSUE TITLE
[Bug] `docker run` in kubernetes raises `unresolved namespace`

### ISSUE THREAD

**Issue by archongum** [apache/dolphinscheduler#16927]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I just want to move below docker setup into kubernetes deployment without "kubernetes" style, just want to run this docker container. 

```sh
docker run -d --name dolphinscheduler-api \
    -e DATABASE="postgresql" \
    -e SPRING_DATASOURCE_URL="jdbc:postgresql://localhost:5432/dolphinscheduler" \
    -e SPRING_DATASOURCE_USERNAME="<USER>" \
    -e SPRING_DATASOURCE_PASSWORD="<PASSWORD>" \
    -e REGISTRY_ZOOKEEPER_CONNECT_STRING="localhost:2181" \
    --net host \
    -d apache/dolphinscheduler-api:3.1.5
```

But raises `unresolved namespace` error.

k8s yaml like this:

```yml
metadata:
  creationTimestamp: null
  labels:
  namespace: dev
spec:
  podPartition:
    stable:
      template:
        metadata:
        spec:
          affinity:
          containers:
          - env:
            image: apache/dolphinscheduler-api:3.1.5
  replicas: 1
  selector:
  updateStrategy:
```

<img width="1188" alt="image" src="https://github.com/user-attachments/assets/5c684624-2319-4a24-b7b9-168469519694" />

### What you expected to happen

Run normally as `docker run` did.

### How to reproduce

See `What happened` session

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
