### ISSUE TITLE
[Bug][DolphinScheduler 3.2.2] alertServer registers Pod name in Zookeeper in Kubernetes environment, causing alert failures

### ISSUE THREAD

**Issue by kaijli-bigdata** [apache/dolphinscheduler#17144]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In DolphinScheduler version 3.2.2, the alertServer service registers its address in Zookeeper using the Pod name (e.g., alert-server-7d6f7b8d8f-zc4h9) instead of a stable or resolvable address.

In a Kubernetes environment, this leads to alert failure, because other components are unable to resolve the Pod name across the cluster or outside the namespace. As a result, alerts are not delivered properly.

![Image](https://github.com/user-attachments/assets/d10ddfb2-eeb5-46e2-8470-d38c03863547)

![Image](https://github.com/user-attachments/assets/8c2c9140-6b1f-4666-9859-a3e0b421a921)

![Image](https://github.com/user-attachments/assets/d28b7bda-f879-4928-8e7e-00189e185214)

### What you expected to happen

The host registered in Zookeeper can be either the alertServer service name or the service IP. This way, the api can call the alertServer service.

### How to reproduce

Deploy DolphinScheduler 3.2.2 in a Kubernetes environment.

Make sure that the alertServer is configured and running as part of the deployment.

Verify that the alertServer registers its address in Zookeeper using the Pod name (e.g., alert-server-7d6f7b8d8f-zc4h9).

Check the Zookeeper service to verify that it contains the Pod name as the registered address.

Try to call the alert server from another service in the cluster using the registered address.

Observe the failure in the alert server connection due to the Pod name not being resolvable by other services.

### Version

3.2.x

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can try specify network in https://github.com/apache/dolphinscheduler/blob/b7fc727865db299b3732928a03c3aff1dbeeeab9/dolphinscheduler-common/src/main/resources/common.properties#L75-L79

**Comment by kaijli-bigdata** [comment]
> You can try specify network in
> 
> [dolphinscheduler/dolphinscheduler-common/src/main/resources/common.properties](https://github.com/apache/dolphinscheduler/blob/b7fc727865db299b3732928a03c3aff1dbeeeab9/dolphinscheduler-common/src/main/resources/common.properties#L75-L79)
> 
> Lines 75 to 79 in [b7fc727](/apache/dolphinscheduler/commit/b7fc727865db299b3732928a03c3aff1dbeeeab9)
> 
>  # network interface preferred like eth0, default: empty 
>  #dolphin.scheduler.network.interface.preferred= 
>   
>  # network interface restrict like docker0,docker1 , default: docker0 
>  dolphin.scheduler.network.interface.restrict=docker0

My current issue is that dolphinscheduler-api cannot call the alert plugin through the dolphinscheduler-alert Pod name. How can I modify the network configuration to make this work?

**Comment by reimuLy** [comment]
![Image](https://github.com/user-attachments/assets/7a6ed814-61ad-4d26-8feb-c2e84c9aba6c)
You can try adding this environment variable, I encountered the same problem, and it worked normally after adding this environment variable

**Comment by reimuLy** [comment]
If it still does not work properly, you can refer to my deployment file:
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    k8s.kuboard.cn/displayName: dolphin平台alert节点
    k8s.kuboard.cn/workload: dolphin-alert
  labels:
    k8s.kuboard.cn/layer: dolphin
    k8s.kuboard.cn/name: dolphin-alert
  name: dolphin-alert
  namespace: big-data
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.kuboard.cn/name: dolphin-alert
  serviceName: dolphin-alert
  template:
    metadata:
      labels:
        k8s.kuboard.cn/name: dolphin-alert
    spec:
      containers:
        - env:
            - name: DATABASE
              value: mysql
            - name: SPRING_DATASOURCE_URL
              value: >-
                jdbc:mysql://*.cotpwdfxy0tl.rds.cn-northwest-1.amazonaws.com.cn:3386/dolphin?useSSL=false&useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false
            - name: SPRING_DATASOURCE_USERNAME
              value: dolphin_eks
            - name: SPRING_DATASOURCE_PASSWORD
              value: *
            - name: SPRING_JACKSON_TIME_ZONE
              value: GMT+8
            - name: REGISTRY_TYPE
              value: jdbc
            - name: spring.cloud.kubernetes.enabled
              value: 'false'
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
          image: >-
            *.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dockerhub/apache/dolphinscheduler-alert-server:3.2.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 50053
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: alert
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 50053
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      setHostnameAsFQDN: true

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: dolphin-alert
  labels:
    k8s.kuboard.cn/layer: dolphin
    k8s.kuboard.cn/name: dolphin-alert
  name: dolphin-alert
  namespace: big-data
spec:
  clusterIP: None
  ports:
    - name: psdsk8
      port: 50052
      protocol: TCP
      targetPort: 50052
  publishNotReadyAddresses: true
  selector:
    k8s.kuboard.cn/name: dolphin-alert
  type: ClusterIP

```
