### ISSUE TITLE
File path write problem in docker

### ISSUE THREAD

**Issue by s348268281** [apache/dolphinscheduler#5526]
想请问下，我是用docker部署的最新版本，要是使用python节点创建一个工作流，内容是新建文件写入helloworld，这个文件路径可以写我部署的服务器的绝对路径吗？这个文件创建后在服务器哪里可以看见呢？我测试了下在可视化下新建了文件，并用python脚本写入，但一直提示IOError: [Errno 13] Permission denied: './test1.txt'，求大佬指教。

**Comment by CalvinKirs** [comment]
Please use Englis.In addition, I see Permission denied

**Comment by s348268281** [comment]
I am using the latest version of Docker deployment. If I use Python node to create a workflow, the content is to create a new file and write to HelloWorld, can this file path write the absolute path of the server I deployed?Where can I see this file on the server after it is created?I tested the new file under the visualization and wrote it with Python script.but the error:IOError: [Errno 13] Permission denied: './test1.txt'，my python script like this:
with open('test1.txt','w',encoding='utf-8') as f1:
    f1.write('hello')

**Comment by CalvinKirs** [comment]
> I am using the latest version of Docker deployment. If I use Python node to create a workflow, the content is to create a new file and write to HelloWorld, can this file path write the absolute path of the server I deployed?Where can I see this file on the server after it is created?I tested the new file under the visualization and wrote it with Python script.but the error:IOError: [Errno 13] Permission denied: './test1.txt'，my python script like this:
> with open('test1.txt','w',encoding='utf-8') as f1:
> f1.write('hello')

It seems that the executing tenant does not have permission to create files

**Comment by s348268281** [comment]
However, I created the tenant with the admin account and did not see any authorized actions on the create tenant page, so what can I do to successfully execute this Python script, create and write to the file?

**Comment by blackberrier** [comment]
@s348268281 
it seems that we can't see file on server unless you have mounted the path where the file is in. See volume and mountVolume for detail.
For the permission problem, you should make sure the problem source is inside docker or server. In my opinion, maybe the problem comes from docker directory permission.
Maybe you can specify absolute file name instead relative one ,and docker directory diffs from server one when mounting volumes.

**Comment by chengshiwen** [comment]
@s348268281 Which version of ds? And please show us the python script. If you want to write the file into the host server, you should use volume

**Comment by chengshiwen** [comment]
@s348268281 In 1.3.6 of docker, it is best to use a tenant named `root`, otherwise it may cause Permission denied problems.

As for volume, you can add the `    - ${PWD}/data:/opt/data` for `dolphinscheduler-worker volumes` in `docker-compose.yml` like:

```yaml
  dolphinscheduler-worker:
    image: apache/dolphinscheduler:latest
    command: worker-server
    environment:
      TZ: Asia/Shanghai
    env_file: config.env.sh
    healthcheck:
      test: ["CMD", "/root/checkpoint.sh", "WorkerServer"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
    - dolphinscheduler-postgresql
    - dolphinscheduler-zookeeper
    volumes:
    - dolphinscheduler-worker-data:/tmp/dolphinscheduler
    - dolphinscheduler-logs:/opt/dolphinscheduler/logs
    - dolphinscheduler-shared-local:/opt/soft
    - dolphinscheduler-resource-local:/dolphinscheduler
    - ${PWD}/data:/opt/data
    restart: unless-stopped
    networks:
    - dolphinscheduler
```

After running `docker-compose up -d`, you can create a python task with the tenant named `root`:
```python
with open('/opt/data/test.txt', 'w') as f:
  f.write('hello world\n')
```

After the task runs successfully, you can view `cat data/test.txt` on the host
