### ISSUE TITLE
[Bug][dolphinschedeler-dao] Failed to obtain JDBC Connection when start with mysql driver via docker

### ISSUE THREAD

**Issue by gk0916** [apache/dolphinscheduler#6014]
**Describe the bug**
Failed to obtain JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'dolphinscheduler'

**To Reproduce**
start with mysql driver via docker

**Expected behavior**
create database 'dolphinscheduler' if not exists, may be modify jdbc url add a param 'createDatabaseIfNotExist=true'

**Which version of Dolphin Scheduler:**
 - [1.3.6-release]

**Comment by chengshiwen** [comment]
@gk0916 Usually for security, the database is best created by the administrator. For this problem, you can run docker-compose like
```yml
  ds-mysql:
    image: mysql:5.7
    container_name: ds-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dolphinscheduler
      - MYSQL_USER=ds_user
      - MYSQL_PASSWORD=dolphinscheduler
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-allowed-packet=128M --default-time_zone='+8:00'
    restart: unless-stopped
    networks:
      - ds_net
```

or just run docker
```shell
docker run -d --name ds-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=dolphinscheduler -e MYSQL_USER=ds_user -e MYSQL_PASSWORD=dolphinscheduler -e TZ=Asia/Shanghai --restart unless-stopped mysql:5.7 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-allowed-packet=128M --default-time_zone='+8:00'
```

**Comment by chengshiwen** [comment]
This is my docker-compose.yml for development:

```yml
version: "3.5"

services:
  # ads-pgsql:
  #   image: bitnami/postgresql:11.11.0
  #   container_name: ads-pgsql
  #   ports:
  #     - 5432:5432
  #   environment:
  #     TZ: Asia/Shanghai
  #     POSTGRESQL_USERNAME: root
  #     POSTGRESQL_PASSWORD: root
  #     POSTGRESQL_DATABASE: dolphinscheduler
  #   restart: unless-stopped
  #   networks:
  #     - ads_net

  ads-mysql:
    image: bitnami/mysql:5.7
    container_name: ads-mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ds_user
      MYSQL_PASSWORD: dolphinscheduler
      MYSQL_DATABASE: dolphinscheduler
    restart: unless-stopped
    networks:
      - ads_net

  ads-zk:
    image: bitnami/zookeeper:3.6.2
    container_name: ads-zk
    ports:
      - 2181:2181
    environment:
      TZ: Asia/Shanghai
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_4LW_COMMANDS_WHITELIST: srvr,ruok,wchs,cons
    restart: unless-stopped
    networks:
      - ads_net

  ads-minio:
    image: bitnami/minio:latest
    container_name: ads-minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      TZ: Asia/Shanghai
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_DEFAULT_BUCKETS: dolphinscheduler
    restart: unless-stopped
    networks:
      - ads_net

networks:
  ads_net:
```

And then modify:
![image](https://user-images.githubusercontent.com/4902714/143418744-9a3e7f53-b08d-458a-b1fe-3af1bc4a25a7.png)
